import type { Metadata } from 'next'
import { Alumni_Sans } from 'next/font/google'
import './globals.css'

const fontsMono = Alumni_Sans({
    variable: '--font-mono',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

const Layout = ({
    children,
}: Readonly<{
    children: React.ReactNode
}>) => {
    return (
        <html lang="en">
            <body className={`${fontsMono.variable} text-text text-xl`}>
                {children}
            </body>
        </html>
    )
}

export default Layout
